# Generated by Django 4.0 on 2022-01-31 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_breed_exerciseneeds_alter_breed_friendliness_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='exerciseneeds',
            new_name='exercise_needs',
        ),
        migrations.RenameField(
            model_name='breed',
            old_name='sheddingamount',
            new_name='shedding_amount',
        ),
        migrations.RenameField(
            model_name='breed',
            old_name='trainability',
            new_name='train_ability',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='favoritefood',
            new_name='favorite_food',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='favoritetoy',
            new_name='favorite_toy',
        ),
    ]
